### PR TITLE
Add better configuration of showing messages, and fix DbAdapter loging during DB errors

### PR DESCRIPTION
**Pull request by Orajo**
Add "view_priority" config param for controlling which errors shows custom error message.

Response refactoring to code optimization and better control by view_priority parameter.
Fix of logging errors through DbAdapter and coused by errors like connection error.

### CODE REVIEW

**Comment by Orajo** [comment]
I have added some fixes after detailed testing

**Comment by DavidHavl** [comment]
Hi Orajo,
Thanks for the good work.
The only thing I am not sure about is the name of the "view_priority". it is not very clear? perhaps more like "displayable_error_levels"?

**Comment by Orajo** [comment]
Yes, you are right. I'll change it.

**Comment by DavidHavl** [comment]
Great, thank you. I will merge your PR as soon as you do.

**Pull request merged**
